//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int feedback_id { get; set; }
        public Nullable<int> oid { get; set; }
        public Nullable<int> rid { get; set; }
        public Nullable<int> did { get; set; }
        public string feedback1 { get; set; }
    }
}
