//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY
    {
        public int historyid { get; set; }
        public Nullable<int> renterid { get; set; }
        public Nullable<int> oid { get; set; }
        public Nullable<int> dressid { get; set; }
        public string rentstartdate { get; set; }
        public string rentenddate { get; set; }
        public string pickingdate { get; set; }



        [NotMapped]
        public List<DRESSIMAGE> images { get; set; }

        [NotMapped]
        public string Reqname { get; set; }

        [NotMapped]
        public string Reqcontact { get; set; }

        [NotMapped]
        public string Reqaddress { get; set; }

        [NotMapped]
        public string Reqcity { get; set; }

        [NotMapped]
        public string Reqstatus { get; set; }

    }
}
