//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DRESSIMAGE> DRESSIMAGEs { get; set; }
        public virtual DbSet<DRESSINFO> DRESSINFOes { get; set; }
        public virtual DbSet<HISTORY> HISTORies { get; set; }
        public virtual DbSet<OWNERFAVORITE> OWNERFAVORITEs { get; set; }
        public virtual DbSet<RECOMEND> RECOMENDs { get; set; }
        public virtual DbSet<RENT> RENTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USERINFO> USERINFOes { get; set; }
        public virtual DbSet<WHISHLIST> WHISHLISTs { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACKs { get; set; }
    }
}
