//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECOMEND
    {
        public int recomended { get; set; }
        public Nullable<int> senderid { get; set; }
        public Nullable<int> receverid { get; set; }
        public Nullable<int> dressid { get; set; }
    }
}
