//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class WHISHLIST
    {
        public int wislist_id { get; set; }
        public Nullable<int> requesterid { get; set; }
        public Nullable<int> dressid { get; set; }
        public string dress_status { get; set; }
        public string availabilty_date { get; set; }

        [NotMapped]
        public List<DRESSIMAGE> images { get; set; }

        [NotMapped]
        public string Oname { get; set; }
        [NotMapped]
        public string Dname { get; set; }
        [NotMapped]
        public string Status { get; set; }
        [NotMapped]
        public int Oid { get; set; }

        [NotMapped]
        public string Contact { get; set; }

        [NotMapped]
        public string Address { get; set; }

        [NotMapped]
        public string City { get; set; }



    }
}
